name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Debug
    - run: cd ${{ github.workspace}} /app/build/outputs/apk/
    - run: ls
    - run: cd debug
    - name: Build with Gradle
      run: ./gradlew app:assembleDebug
    - name: Debug
      run: cd app
    - run: ls
    - run: cd build
    - run: ls
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: ${{ github.workspace}} /app/build/outputs/apk/release/app-release.apk
